name: fidelin_user_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_modular: ^6.3.4
  mobx: ^2.3.3+2
  flutter_mobx: ^2.2.1+1
  dartz: ^0.10.1
  equatable: ^2.0.5
  http: ^1.2.1
  flutter_dotenv: ^5.1.0
  scroll_snap_list: ^0.9.1
  material_design_icons_flutter: ^7.0.7296
  json_annotation: ^4.9.0
  font_awesome_flutter: ^10.7.0
  url_launcher: ^6.3.0
  qr_flutter: ^4.1.0
  flutter_barcode_scanner: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter_native_splash:
  color: "#F22F52"
  image: "assets/app/icon.png"
  android: true
  ios: true

flutter_launcher_icons:
  image_path: "assets/app/icon.png"
  ios: true
  remove_alpha_ios: true
  android: "launcher_icon"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/app/icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mobx_codegen: ^2.6.1
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  faker: ^2.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/white-logo.png
    - assets/images/forgot_password.png
    - assets/images/mail_sent.png
    - assets/images/dialog_success.png
    - .env
